apiVersion: v1
appVersion: "1.0"
version: 0.4.0
description: A sample chart for demonstrating a chart repo hosted on GitHub Pages
name: hello-helm
home: https://github.com/unguiculus/gh-pages-helm-chart-repo-example
maintainers:
  - name: unguiculus
    e-mail: unguiculus@gmail.com
